services:
  db:
    image: 
      postgres:latest
    restart: 
      always
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 10  # (wait longer for PostgreSQL to fully initialize)

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - .env.dev
    volumes:
      - ./backend/src:/app/src
    depends_on:
      db:
        condition: service_healthy  # (only starts when PostgreSQL is fully ready)

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - ./frontend/src:/app/src

volumes:
  pgdata: