services:
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile.dev 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development