# Use official Python image as base
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the application files
COPY requirements.txt .

# Install dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend files
COPY . .

# Expose backend port
EXPOSE 5000

# Command to run the FastAPI app
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]