services:
  db:
    image: 
      postgres:latest
    restart: 
      always
    ports:
      - "5432:5432"
    networks:
      - localnetwork
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 10  # (wait longer for PostgreSQL to fully initialize)

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    networks:
      - localnetwork
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy  # (only starts when PostgreSQL is fully ready)

volumes:
  pgdata:

networks:
  localnetwork:


######

# sudo docker compose -f docker-compose.dev.yml up --build