services:

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public


  # sudo docker compose -f docker-compose.dev.yml up --build