# Use official Python image as base
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the application files
COPY requirements.txt .

# Install dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend files
COPY . .

# Expose backend port
EXPOSE 5001

# Run the Tornado-based Perspective server
CMD ["python", "-m", "src.app"]